### ISSUE TITLE
Black Screen on Mac (Intel)

### ISSUE THREAD

**Issue by tqwewe** [gavlig/kodiki#2]
Thanks for investing your time into such an awesome project!

I've just tried to build it for mac using the two scripts, and after running `./build/bin/kodiki`, the window that loads is just pure black, and the only output in the terminal is "gltf assets loaded!".

Any ideas why it doesn't seem to render on Mac? Thanks!

**Comment by gavlig** [comment]
![image](https://github.com/gavlig/kodiki/assets/668981/566c9a43-9baf-4efd-ba44-763ea6e92016)
It should report fonts loaded too, i suspect that git lfs didnt work. Could you try running `git lfs install` + `git lfs checkout .` in you copy of repo and try running it again?

**Comment by gavlig** [comment]
I just tried building it from scratch and it worked without initializing lfs, but that maybe because lfs was already initialized once? Hard to say. Either way, if that doesnt work, could you check that fonts in assets/fonts are present and look like this?
![image](https://github.com/gavlig/kodiki/assets/668981/723deb4f-2da7-4ca5-8f3b-01ece9e9dbf9)

**Comment by tqwewe** [comment]
I just tried installing the assets with `git lfs install`, `git lfs checkout .`, `git lfs fetch`, and `git lfs pull`.
Then, I ran `./make_build.sh` again, and can verify that there are the font and mesh assets in the `./build/assets` directory (as well as in the root `assets` directory).

Finally, trying to run the app again with `./build/bin/kodiki`, I still get a black screen and only gltf assets loaded, but not the fonts.

**Comment by gavlig** [comment]
Alright, I see three options here:
1. If possible, please archive your copy of repo without folder 'target' and share it with me so we can confirm that there is no corruption there. If not possible, please make sure that your fonts have the same file size as I showed above on that screenshot
2. Did you modify `prepare_runtime.sh` for mac os? by default it assumes you're on windows (I might need to automate that)
3. Some more logs were added in branch `issue_2`, you can check it out (`git fetch origin` + `git checkout issue_2`) and do the same or just run `run.sh` from repo root, that will build and launch Kodiki with `cargo run -r` and some environment variables needed for it to work like that.  
my log output was like this with it: ![image](https://github.com/gavlig/kodiki/assets/668981/ddbc2cba-11bd-4419-9e6f-e1c3be9c4a9b)
4. If you're comfortable with it, just add more logs to `src/kodiki/systems.rs : font_asset_loading_events` to see what's going on there, i'll help you with that too once we're done with logs from `issue_2` branch

**Comment by tqwewe** [comment]
Thanks, I just got it working!

> please make sure that your fonts have the same file size as I showed above on that screenshot

Your comment about the font file size was spot on. They were indeed off, showing only 131/133 bytes.

So, I checked the `./assets/fonts` directory in the root, and the files there were fine. Then, I thought of clearing out with `rm -rf ./build` and rerunning `./make_build.sh`. Oddly, it didn't create an `assets` directory in `./build` this time. This led me to realize that `./prepare_runtime` was the command that actually copied the assets. I tried manually copying with `cp -R ./assets ./build/bin/` and got an error saying `-R` isn't valid. Switching to `-r` did the trick. After copying the assets directory, everything loaded perfectly :)

I think the fix might be that the `prepare_runtime.sh` script needs to use `-r` instead of `-R` for the `cp` commands?

**Comment by gavlig** [comment]
Awesome, thanks for figuring it out! Yes, indeed, build folder had to be cleaned up before reattempting since it copied only lfs links instead of font assets, i didnt think of that. 
As for -r and -R [this](https://ss64.com/osx/cp.html) documentation says that -r is a legacy option, but i'm not very experienced with mac os so if that's what will fix this for other i'll do it no problem. Can you tell me what version of mac os you used when encountering this?

**Comment by tqwewe** [comment]
> As for -r and -R [this](https://ss64.com/osx/cp.html) documentation says that -r is a legacy option, but i'm not very experienced with mac os so if that's what will fix this for other i'll do it no problem. Can you tell me what version of mac os you used when encountering this?

I realised its because I'm using Nushell on my mac. However running the script uses bash so actually it worked fine, only an issue when I manually ran the script.

Also I can confirm that git lsf is indeed required. I'm just building this project on my PC running linux, and noticed the fonts in the root are just the 300 bytes. So might be worth adding the git lsf instructions to the README?

> About working without Helix runtime, it will start and allow you to type and stuff, but most of the Helix functionality wont work, for example syntax highlighting, AST aware movement etc. Basic editing should indeed work though!

Ah right that makes sense since no lsp stuff was working :grin:

**Comment by gavlig** [comment]
for lsp stuff to work you also need to install lsp server, here is a [page about it](https://docs.helix-editor.com/lang-support.html)

And I will add lfs instructions to readme, yes, thank you!
